const drinksData = [
    {
        id: "1",
        nome: "Negroni Clássico",
        categoria: "Gin",
        emoji: "🍸",
        imagem: "images/negroni.jpg",
        descricao: "O clássico aperitivo italiano com equilíbrio perfeito entre amargor e doçura",
        glass: "Old Fashioned",
        technique: "Mexido no copo",
        ingredientes: ["30ml O'Gin London Dry", "30ml Campari", "30ml Martini Rosso", "Casca de laranja"],
        preparo: ["Adicione todos os ingredientes em um copo old fashioned com gelo", "Mexa gentilmente por 30 segundos", "Finalize com casca de laranja espremida sobre a bebida"]
    },
    {
        id: "2",
        nome: "Gin Tônica Premium",
        categoria: "Gin",
        emoji: "🍸",
        imagem: "images/gin-tonica.jpg",
        descricao: "Refrescante e elegante, perfeito para qualquer ocasião",
        glass: "Highball",
        technique: "Montado no copo",
        ingredientes: ["50ml O'Gin London Dry", "150ml água tônica gelada", "Rodelas de limão taiti", "Gelo abundante"],
        preparo: ["Encha um copo highball com gelo", "Adicione o gin", "Complete com água tônica gelada", "Mexa delicadamente", "Finalize com rodelas de limão"]
    },
    {
        id: "3",
        nome: "Old Fashioned Clássico",
        categoria: "Whiskey",
        emoji: "🥃",
        imagem: "images/old-fashioned.jpg",
        descricao: "O whiskey drink mais clássico de todos os tempos",
        glass: "Old Fashioned",
        technique: "Mexido no copo",
        ingredientes: ["60ml Jim Beam Bourbon", "1 torrão de açúcar cristal", "3-4 dashes Angostura Bitter", "Casca de laranja", "1 cereja (opcional)"],
        preparo: ["Dissolva o açúcar com o bitter e uma pequena quantidade de água no copo", "Adicione gelo e o bourbon", "Mexa gentilmente", "Expresse óleos da casca de laranja sobre o drink", "Finalize com cereja se desejar"]
    },
    {
        id: "4",
        nome: "Caipirinha Tradicional",
        categoria: "Cachaça",
        emoji: "🍹",
        imagem: "images/caipirinha.jpg",
        descricao: "O drink nacional brasileiro, refrescante e autêntico",
        glass: "Old Fashioned",
        technique: "Macerado no copo",
        ingredientes: ["60ml Cachaça (Vira Copos ou Joseph Bless)", "1/2 limão taiti cortado em pedaços", "2 colheres de chá de açúcar cristal", "Gelo picado"],
        preparo: ["Coloque os pedaços de limão no copo old fashioned", "Adicione açúcar", "Macere delicadamente para extrair sucos", "Encha com gelo picado", "Adicione cachaça e mexa bem"]
    },
    {
        id: "5",
        nome: "Mojito",
        categoria: "Rum",
        emoji: "🍃",
        imagem: "images/mojito.jpg",
        descricao: "Cubano clássico com hortelã fresca e muito sabor",
        glass: "Highball",
        technique: "Macerado no copo",
        ingredientes: ["60ml Bacardi Carta Blanca", "30ml suco de limão taiti fresco", "20ml xarope simples", "8-10 folhas de hortelã fresca", "Água com gás", "Gelo picado"],
        preparo: ["Macere delicadamente hortelã com xarope no copo", "Adicione rum e suco de limão", "Encha com gelo picado", "Complete com água com gás", "Mexa gentilmente", "Decore com ramo de hortelã"]
    },
    {
        id: "6",
        nome: "Margarita Clássica",
        categoria: "Tequila",
        emoji: "🍹",
        descricao: "O drink mexicano mais famoso do mundo",
        glass: "Old Fashioned (borda com sal)",
        technique: "Balançado",
        ingredientes: ["60ml Tequila el Jimador Reposado", "30ml Triple Sec (Stock Curaçau claro)", "30ml suco de limão taiti fresco", "Sal para a borda", "Rodela de limão"],
        preparo: ["Passe limão na borda do copo e mergulhe no sal", "Em uma coqueteleira, agite todos os ingredientes com gelo", "Coe para copo old fashioned com gelo fresco", "Decore com rodela de limão"]
    },
    {
        id: "7",
        nome: "Aperol Spritz",
        categoria: "Aperitivos",
        emoji: "🥂",
        descricao: "O aperitivo italiano perfeito para o fim de tarde",
        glass: "Taça de vinho",
        technique: "Montado no copo",
        ingredientes: ["60ml Aperol", "90ml água com gás gelada", "Fatia de laranja", "Gelo abundante"],
        preparo: ["Encha taça de vinho com gelo", "Adicione Aperol", "Complete com água com gás", "Mexa delicadamente", "Decore com fatia de laranja"]
    },
    {
        id: "8",
        nome: "Sake Martini",
        categoria: "Saquê",
        emoji: "🍶",
        descricao: "Elegante fusão entre oriente e ocidente",
        glass: "Taça de martini",
        technique: "Mexido",
        ingredientes: ["60ml Saquê japonês gelado", "15ml O'Gin London Dry", "10ml Martini Extra Dry", "Casca de limão"],
        preparo: ["Misture todos os ingredientes em copo misturador com gelo", "Mexa por 30 segundos", "Coe para taça de martini gelada", "Finalize com casca de limão"]
    },
    {
        id: "9",
        nome: "Limonada Suíça",
        categoria: "Sem Álcool",
        emoji: "🍋",
        descricao: "Refrescante e natural, com o limão integral",
        glass: "Highball",
        technique: "Batido no liquidificador",
        ingredientes: ["1 limão taiti inteiro", "2 colheres de sopa de açúcar cristal", "200ml água gelada", "Gelo"],
        preparo: ["Corte limão em rodelas", "Bata rapidamente no liquidificador com água e açúcar", "Coe e sirva com gelo"]
    },
    {
        id: "10",
        nome: "Piña Colada",
        categoria: "Rum",
        emoji: "🥥",
        descricao: "Tropical e cremoso, como umas férias no Caribe",
        glass: "Taça de vinho",
        technique: "Balançado",
        ingredientes: ["60ml Bacardi Carta Branca", "60ml leite de coco", "60ml suco de abacaxi fresco", "15ml xarope simples", "Gelo"],
        preparo: ["Em uma coqueteleira, agite todos os ingredientes vigorosamente com gelo", "Coe para taça de vinho com gelo fresco", "Decore com abacaxi e cereja"]
    },
    {
        id: "11",
        nome: "Caipirinha de Morango",
        categoria: "Cachaça",
        emoji: "🍓",
        descricao: "Versão doce e frutal da nossa caipirinha",
        glass: "Old Fashioned",
        technique: "Macerado no copo",
        ingredientes: ["60ml Cachaça", "4-5 morangos frescos", "2 colheres de chá de açúcar cristal", "Gelo picado"],
        preparo: ["Macere morangos com açúcar no copo", "Adicione gelo e cachaça", "Mexa bem"]
    },
    {
        id: "12",
        nome: "Whiskey Sour",
        categoria: "Whiskey",
        emoji: "🥃",
        descricao: "Azedinho equilibrado que conquista qualquer paladar",
        glass: "Old Fashioned",
        technique: "Balançado",
        ingredientes: ["60ml Jameson Irish Whiskey", "30ml suco de limão taiti fresco", "20ml xarope simples", "Rodela de limão"],
        preparo: ["Em uma coqueteleira, agite todos os ingredientes com gelo vigorosamente", "Coe para copo old fashioned com gelo fresco", "Decore com rodela de limão"]
    },
    {
        id: "13",
        nome: "Fernet com Coca",
        categoria: "Aperitivos",
        emoji: "🥃",
        descricao: "Combinação única que divide opiniões e conquista paladares",
        glass: "Highball",
        technique: "Montado no copo",
        ingredientes: ["30ml Fernet-Branca", "150ml Coca-Cola gelada", "Rodela de limão", "Gelo"],
        preparo: ["Encha copo highball com gelo", "Adicione Fernet-Branca", "Complete com Coca-Cola", "Mexa gentilmente", "Decore com rodela de limão"]
    },
    {
        id: "14",
        nome: "Tequila Sunrise",
        categoria: "Tequila",
        emoji: "🌅",
        descricao: "Visual impressionante como um nascer do sol",
        glass: "Highball",
        technique: "Montado no copo",
        ingredientes: ["60ml Tequila el Jimador Reposado", "120ml suco de laranja fresco", "15ml mel", "Rodela de laranja"],
        preparo: ["Encha copo highball com gelo", "Adicione tequila e suco de laranja", "Mexa bem", "Despeje mel lentamente pela lateral do copo", "Decore com rodela de laranja"]
    },
    {
        id: "15",
        nome: "Batida de Coco",
        categoria: "Cachaça",
        emoji: "🥥",
        descricao: "Cremosa e tropical, perfeita para o verão brasileiro",
        glass: "Highball",
        technique: "Balançado",
        ingredientes: ["60ml Cachaça", "100ml leite de coco", "15ml xarope simples", "Gelo", "Coco ralado"],
        preparo: ["Em uma coqueteleira, agite todos os ingredientes vigorosamente com gelo", "Coe para copo alto com gelo fresco", "Decore com coco ralado"]
    },
    {
        id: "16",
        nome: "Martini Extra Seco",
        categoria: "Gin",
        emoji: "🫒",
        descricao: "O clássico dos clássicos, elegante e sofisticado",
        glass: "Taça de martini",
        technique: "Mexido",
        ingredientes: ["60ml O'Gin London Dry", "10ml Martini Extra Dry", "Azeitona ou casca de limão"],
        preparo: ["Resfrie todos os ingredientes", "Misture gin e vermouth com gelo", "Mexa por 30 segundos", "Coe para taça gelada", "Decore com azeitona"]
    },
    {
        id: "17",
        nome: "Americano",
        categoria: "Aperitivos",
        emoji: "🍸",
        descricao: "Aperitivo milionário, predecessor do Negroni",
        glass: "Highball",
        technique: "Montado no copo",
        ingredientes: ["30ml Campari", "30ml Martini Rosso", "Água com gás", "Casca de laranja", "Gelo"],
        preparo: ["Adicione Campari e vermouth com gelo", "Complete com água com gás", "Mexa gentilmente", "Finalize com casca de laranja"]
    },
    {
        id: "18",
        nome: "Smoothie de Morango",
        categoria: "Sem Álcool",
        emoji: "🍓",
        descricao: "Nutritivo e delicioso, carregado de vitaminas",
        glass: "Taça de suco",
        technique: "Batido no liquidificador",
        ingredientes: ["8-10 morangos congelados", "100ml leite de coco", "1 colher de sopa de mel", "Coco ralado", "Gelo"],
        preparo: ["Bata todos os ingredientes no liquidificador", "Sirva em taça de suco", "Decore com coco ralado"]
    },
    {
        id: "19",
        nome: "Negroni com Aperol",
        categoria: "Gin",
        emoji: "🍊",
        descricao: "Versão mais suave e cítrica do Negroni clássico",
        glass: "Old Fashioned",
        technique: "Mexido no copo",
        ingredientes: ["30ml O'Gin London Dry", "30ml Aperol", "30ml Martini Rosso", "Casca de laranja"],
        preparo: ["Mesmo preparo do Negroni clássico", "Resultará em um drink menos amargo e mais cítrico"]
    },
    {
        id: "20",
        nome: "Tom Collins",
        categoria: "Gin",
        emoji: "🍸",
        descricao: "Refrescante e espumante, perfeito para dias quentes",
        glass: "Highball",
        technique: "Balançado",
        ingredientes: ["50ml O'Gin London Dry", "25ml suco de limão taiti fresco", "15ml xarope simples", "Água com gás", "Rodela de limão"],
        preparo: ["Em uma coqueteleira, agite gin, suco de limão e xarope com gelo", "Coe para copo highball com gelo fresco", "Complete com água com gás", "Decore com rodela de limão"]
    },
    {
        id: "21",
        nome: "Fitzgerald",
        categoria: "Gin",
        emoji: "🍸",
        imagem: "images/fitzgerald.jpeg",
        descricao: "Elegante e equilibrado, com toque de bitter",
        glass: "Taça de martini ou Old Fashioned",
        technique: "Balançado",
        ingredientes: ["45ml O'Gin London Dry", "22ml suco de limão taiti fresco", "22ml xarope simples", "2 dashes Angostura Bitter", "Casca de limão"],
        preparo: ["Em uma coqueteleira, agite todos os ingredientes vigorosamente com gelo", "Coe para taça de martini ou copo old fashioned gelado", "Finalize com casca de limão espremida sobre o drink"]
    },
    {
        id: "22",
        nome: "Highball Japonês",
        categoria: "Whiskey",
        emoji: "🥃",
        descricao: "Minimalista e refrescante, seguindo tradição japonesa",
        glass: "Highball",
        technique: "Montado no copo",
        ingredientes: ["50ml Jameson Irish Whiskey", "150ml água com gás gelada", "Gelo abundante", "Casca de limão"],
        preparo: ["Encha copo highball com gelo e mexa para resfriar", "Descarte água derretida", "Adicione whiskey", "Complete gentilmente com água com gás", "Mexa 3-4 vezes no sentido horário", "Finalize com casca de limão"]
    },
    {
        id: "23",
        nome: "Manhattan",
        categoria: "Whiskey",
        emoji: "🍸",
        descricao: "Sofisticação pura em forma de drink",
        glass: "Taça de martini ou Old Fashioned",
        technique: "Mexido",
        ingredientes: ["60ml Ballantine's 17 anos", "30ml Martini Rosso", "3 dashes Angostura Bitter", "Cereja ou casca de laranja"],
        preparo: ["Misture todos os ingredientes em copo misturador com gelo", "Mexa por 30 segundos", "Coe para taça de martini ou copo old fashioned", "Decore com cereja ou casca de laranja"]
    },
    {
        id: "24",
        nome: "Caipirinha de Gengibre",
        categoria: "Cachaça",
        emoji: "🫚",
        descricao: "Picante e revigorante, com toque energizante",
        glass: "Old Fashioned",
        technique: "Macerado no copo",
        ingredientes: ["60ml Cachaça", "1/4 limão taiti", "1 fatia fina de gengibre fresco", "2 colheres de chá de açúcar cristal", "Gelo picado"],
        preparo: ["Macere limão e gengibre com açúcar", "Adicione gelo e cachaça", "Mexa bem"]
    },
    {
        id: "25",
        nome: "Rabo de Galo",
        categoria: "Cachaça",
        emoji: "🐓",
        descricao: "Drink brasileiro sofisticado com personalidade única",
        glass: "Old Fashioned",
        technique: "Mexido",
        ingredientes: ["45ml Cachaça", "22ml Martini Rosso", "8ml Campari", "Casca de laranja"],
        preparo: ["Misture todos os ingredientes com gelo", "Mexa bem e coe", "Sirva em copo old fashioned com gelo", "Finalize com casca de laranja"]
    },
    {
        id: "26",
        nome: "Macunaíma",
        categoria: "Cachaça",
        emoji: "🇧🇷",
        imagem: "images/macunaima.jpeg",
        descricao: "Homenagem ao herói brasileiro com toque de Fernet",
        glass: "Barriquinha ou Old Fashioned",
        technique: "Balançado",
        ingredientes: ["50ml Cachaça (preferencialmente Vira Copos ou Joseph Bless)", "20ml suco de limão taiti fresco", "15ml xarope simples", "7ml Fernet-Branca"],
        preparo: ["Em uma coqueteleira, agite todos os ingredientes vigorosamente com gelo", "Coe para copo barriquinha ou old fashioned gelado", "Sirva sem gelo e sem decoração", "Coloque guardanapo dobrado embaixo do copo (estilo Boca de Ouro)"]
    },
    {
        id: "27",
        nome: "Daiquiri",
        categoria: "Rum",
        emoji: "🍸",
        descricao: "Puro equilíbrio entre rum, limão e açúcar",
        glass: "Taça de martini",
        technique: "Balançado",
        ingredientes: ["60ml Bacardi Carta Branca", "25ml suco de limão taiti fresco", "15ml xarope simples", "Rodela de limão"],
        preparo: ["Em uma coqueteleira, agite todos os ingredientes vigorosamente com gelo", "Coe para taça de martini gelada", "Decore com rodela de limão"]
    },
    {
        id: "28",
        nome: "Cuba Libre",
        categoria: "Rum",
        emoji: "🇨🇺",
        descricao: "Liberdade cubana em forma de drink refrescante",
        glass: "Highball",
        technique: "Montado no copo",
        ingredientes: ["50ml Bacardi Carta Branca", "150ml Coca-Cola", "15ml suco de limão taiti fresco", "Rodela de limão", "Gelo"],
        preparo: ["Encha copo highball com gelo", "Adicione rum e suco de limão", "Complete com Coca-Cola", "Mexa gentilmente", "Decore com rodela de limão"]
    },
    {
        id: "29",
        nome: "Rum Punch Tropical",
        categoria: "Rum",
        emoji: "🌴",
        descricao: "Explosão tropical de sabores em cada gole",
        glass: "Highball",
        technique: "Balançado",
        ingredientes: ["60ml Bacardi Carta Branca", "30ml suco de maracujá", "20ml suco de limão taiti", "15ml xarope simples", "Água com gás", "Fatias de frutas tropicais"],
        preparo: ["Em uma coqueteleira, agite rum, sucos e xarope com gelo", "Coe para copo highball com gelo fresco", "Complete com água com gás", "Decore com frutas tropicais"]
    },
    {
        id: "30",
        nome: "Paloma",
        categoria: "Tequila",
        emoji: "🕊️",
        descricao: "A pomba mexicana refrescante e elegante",
        glass: "Highball",
        technique: "Balançado",
        ingredientes: ["60ml Tequila el Jimador Reposado", "20ml suco de limão taiti fresco", "15ml xarope simples", "Água com gás", "Pitada de sal", "Rodela de limão"],
        preparo: ["Em uma coqueteleira, agite tequila, suco de limão, xarope e sal com gelo", "Coe para copo highball com gelo fresco", "Complete com água com gás", "Decore com rodela de limão"]
    },
    {
        id: "31",
        nome: "Margarita de Morango",
        categoria: "Tequila",
        emoji: "🍓",
        descricao: "Versão frutal da clássica Margarita mexicana",
        glass: "Old Fashioned (borda com sal)",
        technique: "Balançado",
        ingredientes: ["60ml Tequila el Jimador Reposado", "30ml Triple Sec", "30ml suco de limão taiti", "4-5 morangos frescos", "1 colher de chá de açúcar cristal", "Sal para borda"],
        preparo: ["Macere morangos com açúcar", "Adicione demais ingredientes e agite com gelo na coqueteleira", "Coe para copo com borda salgada", "Decore com morango"]
    },
    {
        id: "32",
        nome: "Negroni Sbagliato",
        categoria: "Aperitivos",
        emoji: "🥂",
        descricao: "O Negroni 'errado' que virou tendência mundial",
        glass: "Taça de vinho",
        technique: "Montado no copo",
        ingredientes: ["30ml Campari", "30ml Martini Rosso", "Água com gás", "Casca de laranja"],
        preparo: ["Misture Campari e vermouth em taça de vinho com gelo", "Complete com água com gás", "Finalize com casca de laranja"]
    },
    {
        id: "33",
        nome: "Sake Highball",
        categoria: "Saquê",
        emoji: "🍶",
        descricao: "Elegância japonesa em sua forma mais pura",
        glass: "Highball",
        technique: "Montado no copo",
        ingredientes: ["60ml Saquê japonês", "150ml água com gás gelada", "Casca de limão siciliano", "Gelo"],
        preparo: ["Encha copo highball com gelo", "Adicione saquê", "Complete com água com gás", "Mexa delicadamente", "Finalize com casca de limão siciliano"]
    },
    {
        id: "34",
        nome: "Sake Sour",
        categoria: "Saquê",
        emoji: "🍶",
        descricao: "Encontro delicado entre oriente e acidez cítrica",
        glass: "Old Fashioned",
        technique: "Balançado",
        ingredientes: ["60ml Saquê japonês", "25ml suco de limão siciliano fresco", "20ml mel dissolvido em água morna", "Rodela de limão siciliano"],
        preparo: ["Em uma coqueteleira, agite todos os ingredientes com gelo", "Coe para copo old fashioned com gelo fresco", "Decore com rodela de limão siciliano"]
    },
    {
        id: "35",
        nome: "Caipiroska de Açaí",
        categoria: "Especiais",
        emoji: "🫐",
        descricao: "Superfood brasileiro em versão alcoólica energética",
        glass: "Old Fashioned",
        technique: "Macerado no copo",
        ingredientes: ["60ml O'Gin London Dry", "2 colheres de sopa de polpa de açaí", "1/2 limão taiti", "2 colheres de chá de açúcar cristal", "Gelo picado"],
        preparo: ["Macere limão com açúcar", "Adicione polpa de açaí", "Adicione gin e gelo", "Mexa bem"]
    },
    {
        id: "36",
        nome: "Batida de Maracujá",
        categoria: "Especiais",
        emoji: "🥭",
        descricao: "O sabor tropical brasileiro mais autêntico",
        glass: "Highball",
        technique: "Balançado",
        ingredientes: ["60ml Cachaça", "Polpa de 2 maracujás", "15ml xarope simples", "100ml água de coco", "Gelo"],
        preparo: ["Em uma coqueteleira, agite todos os ingredientes vigorosamente com gelo", "Coe para copo alto com gelo fresco", "Decore com sementes de maracujá"]
    },
    {
        id: "37",
        nome: "Quentão",
        categoria: "Especiais",
        emoji: "🔥",
        descricao: "Tradição junina que aquece o coração brasileiro",
        glass: "Caneca ou copo de vidro temperado",
        technique: "Fervido",
        ingredientes: ["60ml Cachaça", "200ml água", "2 colheres de sopa de açúcar mascavo", "1 pau de canela", "3 cravos-da-índia", "Casca de 1/4 laranja", "1 fatia de gengibre"],
        preparo: ["Ferva água com especiarias por 5 minutos", "Adicione açúcar mascavo", "Coe e adicione cachaça", "Sirva quente"]
    },
    {
        id: "38",
        nome: "Rabo de Galo Premium",
        categoria: "Especiais",
        emoji: "🐓",
        descricao: "Versão premium do clássico brasileiro",
        glass: "Old Fashioned",
        technique: "Mexido",
        ingredientes: ["45ml Cachaça Joseph Bless \"Golden Bless\"", "20ml Martini Bianco", "10ml Aperol", "2 dashes Angostura Bitter", "Casca de laranja"],
        preparo: ["Misture todos os ingredientes com gelo", "Mexa por 30 segundos", "Coe para copo old fashioned com gelo grande", "Finalize com casca de laranja"]
    },
    {
        id: "39",
        nome: "Suco de Maracujá com Hortelã",
        categoria: "Sem Álcool",
        emoji: "🥭",
        descricao: "Aromático e refrescante, com toque herbáceo",
        glass: "Highball",
        technique: "Macerado no copo",
        ingredientes: ["Polpa de 3 maracujás", "8-10 folhas de hortelã", "2 colheres de sopa de açúcar cristal", "250ml água gelada", "Gelo"],
        preparo: ["Macere hortelã com açúcar", "Adicione polpa de maracujá e água", "Mexa bem e sirva com gelo"]
    },
    {
        id: "40",
        nome: "Água Saborizada de Gengibre",
        categoria: "Sem Álcool",
        emoji: "🫚",
        descricao: "Digestiva e energizante, com propriedades medicinais",
        glass: "Highball",
        technique: "Macerado no copo",
        ingredientes: ["3 fatias finas de gengibre fresco", "1 colher de chá de mel", "Suco de 1/2 limão taiti", "300ml água com gás", "Gelo", "Hortelã para decorar"],
        preparo: ["Macere gengibre com mel", "Adicione suco de limão", "Complete com água com gás", "Decore com hortelã"]
    }
]; 

// Tornar os dados disponíveis globalmente
window.drinksData = drinksData;